---
- name: ensure vpopmail database exists
  mysql_db:
    name: vpopmail
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: ensure vpopmail user exists and set up privileges
  mysql_user:
    name: vpopmail
    password: "{{ mariadb_vpopmail_password }}"
    priv: 'vpopmail.*:ALL'
    host: localhost
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
