---
- name: remove postfix
  yum:
    name: postfix
    state: removed

- name: add EPEL repository
  yum:
    name: epel-release
    state: latest

- name: install yum-plugin-priorities
  yum:
    name: yum-plugin-priorities
    state: latest

- name: get qmt rpm
  get_url:
    src: https://github.com/qmtoaster/release/raw/master/qmt-release-{{ qmt_version }}.qt.el7.noarch.rpm
    dest: /tmp/qmt-release-{{ qmt_version }}.qt.el7.noarch.rpm
    checksum: sha256:ca74e9b77658f4c3686a21d9909384ee74124bbc3d41bb58f31766d6b3b00874

- name: install qmt rpm
  yum:
    name: /tmp/qmt-release-{{ qmt_version }}.qt.el7.noarch.rpm
    state: present

- name: install dependencies
  action: >
      yum name={{ item }} state=present update_cache=yes
  with_items:
    - rsync
    - bind-utils
    - bind
    - net-tools
    - zlib-devel
    - mariadb-server
    - mariadb
    - mariadb-devel
    - libev-devel
    - httpd
    - php
    - mrtg
    - expect
    - libidn-devel
    - aspell
    - tmpwatch
    - perl-Time-HiRes
    - perl-ExtUtils-MakeMaker
    - perl-Archive-Tar
    - perl-Digest-SHA
    - perl-HTML-Parser
    - perl-IO-Zlib
    - perl-Net-DNS
    - perl-NetAddr-IP
    - perl-Crypt-OpenSSL-Bignum
    - perl-Digest-SHA1
    - perl-Encode-Detect
    - perl-Geo-IP
    - perl-IO-Socket-SSL
    - perl-Mail-DKIM
    - perl-Razor-Agent
    - perl-Sys-Syslog
    - perl-Net-CIDR-Lite
    - perl-DB_File
    - bzip2-devel
    - check-devel
    - curl-devel
    - gmp-devel
    - ncurses-devel
    - libxml2-devel
    - python-devel
    - sqlite-devel
    - postgresql-devel
    - openldap-devel
    - quota-devel
    - libcap-devel
    - pam-devel
    - clucene-core-devel
    - expat-devel
    - emacs
    - ocaml
    - procmail
    - wget
    - logwatch
    - vsftpd
    - acpid
    - acpid-sysvinit
    - at
    - autofs
    - ntp
    - smartmontools
    - mod_ssl
    - fail2ban
    - perl-Sys-Hostname-Long
    - perl-Mail-DomainKeys
    - perl-Mail-SPF-Query
    - nfs-utils
